name: financialui
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: any
  shared_preferences: any
  path_provider: any
  url_strategy: any
  flutter_typeahead: any
  shimmer_animation: any
  pointer_interceptor: any
  search_choices: any
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/gifs/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/font/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/font/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Urbanist-Light.ttf
          weight: 300
        - asset: assets/font/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/font/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/font/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/font/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/font/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Urbanist-Black.ttf
          weight: 900
